services:
  kokoro-web:
    image: ghcr.io/eduardolat/kokoro-web:latest
    ports:
      - "8542:3000"
    environment:
      - KW_SECRET_API_KEY=${KW_SECRET_API_KEY}
    volumes:
      - ./DATA/tts/kokoro/cache:/kokoro/cache
    restart: unless-stopped